### ISSUE TITLE
CEPs não cadastrados

### ISSUE THREAD

**Issue by JGRB-0** [mstuttgart/brazilcep#92]
Estou fazendo um bot para automatizar o cadastro de NFEs no site de uma contadora. O formulário solicita o município onde a NFE foi emitida. Para colocar o município, estou usando o BrazilCEP. Porém, ao tentar encontrar o município de Santa Rita do Sapucaí - MG, a biblioteca me informa que não encontrou esse CEP. Creio que seja porque o município recentemente mudou seus CEPs para CEP por rua; antes era apenas um para todo o município. Alguém consegue me ajudar?

CEP que usei e deu erro: 37538628

**Comment by mstuttgart** [comment]
Olá @JGRB-0 , primeiramente, obrigado por usar a Brazilcep!

Consigo te ajudar sim. No caso, pelo que pesquisei aqui, apenas a API do [ViaCEP](https://viacep.com.br/ws/37538628/json/) esta com os CEP de Santa Rita atualizados: https://viacep.com.br/ws/37538628/json/

Então na busca, você pode indicar para a Brazilcep usar o servidor da ViaCEP, assim:

```python
import brazilcep

address = brazilcep.get_address_from_cep('37538628', webservice=brazilcep.WebService.VIACEP)

print(address)
```

**Comment by JGRB-0** [comment]
Acabei de testar aqui e funcionou perfeitamente. Muito obrigado!
