### ISSUE TITLE
Instabilidade na requisição da API

### ISSUE THREAD

**Issue by JGRB-0** [mstuttgart/brazilcep#96]
Estou usando a ferramenta de voces em um projeto particular.  Especificamente hoje, esta bem lento para conseguir fazer as requisições.
Gostaria de saber se a API passou ou esta passando por instabilidades para saber se é o server ou  o meu código

OBS: Faço as requisições usando o comando:
` address = brazilcep.get_address_from_cep(f"{municipio}", webservice=brazilcep.WebService.VIACEP)`

**Comment by mstuttgart** [comment]
@JGRB-0 Bom dia. Tudo bem? 

Não notei nenhum nenhuma instalabilidade no uso da lib (pelo não que tenham me comunicado), mas pode ser sim que o servidor do VIACEP esteja mesmo instavel no momento que você fez as consultas (principalmente no caso do VIACEP, de uns tempos pra cá). Tente executar a consulta com outro API

```python
address = brazilcep.get_address_from_cep(f"{municipio}", webservice=brazilcep.WebService.OPENCEP)
```
